### PR TITLE
Fixed an issue with the gulpfile

### PR DESCRIPTION
**Pull request by amrsekilly**
I was getting an error when trying to run gulp. Now it works, was it just me? And did this fix it for you too if you had any errors?

### CODE REVIEW

**Comment by atjonathan** [comment]
@amrsekilly, I don't get any errors.
What about you @Bouncey ?

**Comment by amrsekilly** [comment]
Ok, I've removed the node_modules directory, and reverted back to the last commit the project had. Then I reinstalled the node modules and it still produces this error 

screenshot 2016-07-06 19 38 26

**Comment by atjonathan** [comment]
@amrsekilly, thanks. Yeh I hadn't got the latest changes locally :+1:

**Comment by amrsekilly** [comment]
You're welcome! 😄

**Comment by Bouncey** [comment]
Weird.

It was working fine for me this morning...

Sure, if it works for you guys now it's not a problem

Thanks for contributing :tada:

**Pull request merged**
