### PR TITLE
fixed "tag search disables other images modal" #48

### LINKED ISSUE #48: tag search disables other images modal
If you search for a certain tag then you delete that search and go back to the home page you can't expand any image to a modal by clicking on it except for the image that matches the previous tag search.

I'll try to investigate that further.

### PR DESCRIPTION
**Pull request by amrsekilly**
Closes #48

### CODE REVIEW

**Comment by atjonathan** [comment]
#### **LGTM :+1:**

Thanks so much for contributing :tada:
This bug haa been nagging me for some time!!

**Comment by amrsekilly** [comment]
Thanks, @atjonathan!! ❤️

**Comment by amrsekilly** [comment]
@atjonathan I'm sorry, I had to merge that with the gh-pages not the master. Can you do that please in order for the change to take effect?

**Comment by atjonathan** [comment]
@amrsekilly, no you are right to merge it into master :smiley:
I will have it merged into gh-pages tomorrow, once I've finished some other fixes 👍

**Pull request merged**
