### PR TITLE
Minify Files with gulp

### PR DESCRIPTION
**Pull request by Bouncey**
Minify's `html`, `css` and `js` files

### CODE REVIEW

**Comment by Bouncey** [comment]
Would require you to `npm install` again

**Comment by atjonathan** [comment]
@Bouncey, you have conflicts :stuck_out_tongue_winking_eye:

**Comment by Bouncey** [comment]
I'm not surprised, let me know if your merging the favicon one, I'll rebase after that if you do

**Comment by Bouncey** [comment]
ha, ok

**Comment by atjonathan** [comment]
@Bouncey, lol just did :+1:

**Comment by Bouncey** [comment]
I simply cannot squash these commits...... losing my mind

**Comment by atjonathan** [comment]
@Bouncey, I'll squash in-browser :stuck_out_tongue_winking_eye:

**Comment by atjonathan** [comment]
@Bouncey can you add the favicon files to the correct folder structure?

**Comment by Bouncey** [comment]
@atjonathan What do you mean about the favicons?

**Comment by atjonathan** [comment]
@Bouncey currently the favicons are in a folder in root. Should they not be moved to `/static` or `/src`?

**Comment by Bouncey** [comment]
I see what you mean. It works as is, but can jig it about for consistency

**Comment by Bouncey** [comment]
Woo!! One commit :tada:!!

**Comment by atjonathan** [comment]
Thanks @Bouncey :heart:

**Comment by Bouncey** [comment]
Ugh... 

someone forgot to delete the favicon folder in `root`

**Pull request merged**
