### PR TITLE
Grid fix

### LINKED ISSUE #7: Fix Grid Issues
This would require giving each photo item a fixed width.

### PR DESCRIPTION
**Pull request by Bouncey**
closes #7 

With more work we could make it more like pintrest

### CODE REVIEW

**Comment by atjonathan** [comment]
#### **LGTM :+1:**
Thanks for helping :smile: 

The next step is to make it more like pintrest, feel free to raise an issue with the details and make a pull request if all seems well :wink:

**Comment by sanskar-modi** [comment]
well i searched and found out that there is a [plugin Masonary](http://masonry.desandro.com/) for doing that pintrest thing.

**Comment by atjonathan** [comment]
@sanskar-modi, thanks looks interesting, would you mind adding it?

**Comment by sanskar-modi** [comment]
i will try it

**Pull request merged**
